#!/usr/bin/env python3
"""TIN-2709 C2b batch parity gate.

Proves that `ptoon redact-batch` produces, for each document, exactly what
`ptoon redact` produces for that document in isolation. If the two agree
byte-for-byte across the whole fixture corpus, then the `coforall` fan-in, the
length-prefixed framing, and the input-order guarantee are all correct: batching
is a pure throughput optimization with zero semantic drift, and no document's
result can leak into another's.

Requires the built binary via `PROMPT_TOON_PTOON` (remote-only nix lane; this
runs inside the ptoon-parity derivation where the binary is present). Fixtures
come from `fixtures/inputs/` (regenerated by tools/gen_fixtures.py). Exits
nonzero on any divergence so the derivation fails closed on a batch regression.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INPUTS = ROOT / "fixtures" / "inputs"

FINDINGS_PREFIX = b"findings:"


def _binary() -> str:
    binary = os.environ.get("PROMPT_TOON_PTOON")
    if not binary:
        print("SKIP: PROMPT_TOON_PTOON not set; nothing to diff.")
        sys.exit(0)
    return binary


def run_redact_single(binary: str, data: bytes) -> tuple[list[str], bytes]:
    """One `ptoon redact` call -> (findings list, redacted bytes)."""
    proc = subprocess.run([binary, "redact"], input=data, capture_output=True, check=True)
    out = proc.stdout
    if not out.startswith(FINDINGS_PREFIX):
        raise AssertionError("redact output missing findings header")
    nl = out.index(b"\n")
    findings_text = out[len(FINDINGS_PREFIX):nl].decode("utf-8")
    findings = [x for x in findings_text.split(",") if x]
    return findings, out[nl + 1:]


def frame_batch(docs: list[bytes]) -> bytes:
    """<n>\\n then per doc <byteLen>\\n <raw bytes>."""
    parts: list[bytes] = [str(len(docs)).encode(), b"\n"]
    for d in docs:
        parts += [str(len(d)).encode(), b"\n", d]
    return b"".join(parts)


def parse_batch(data: bytes) -> list[tuple[dict, bytes]]:
    """<n>\\n then per doc <metaJson>\\n <redactedLen>\\n <redacted bytes>."""
    pos = 0

    def read_line() -> bytes:
        nonlocal pos
        nl = data.index(b"\n", pos)
        line = data[pos:nl]
        pos = nl + 1
        return line

    n = int(read_line())
    results: list[tuple[dict, bytes]] = []
    for _ in range(n):
        meta = json.loads(read_line().decode("utf-8"))
        blen = int(read_line())
        if blen < 0:
            raise AssertionError(f"negative body length for result {len(results)}")
        if pos + blen > len(data):
            raise AssertionError(
                f"result {len(results)} declares {blen} bytes with {len(data) - pos} remaining"
            )
        blob = data[pos:pos + blen]
        pos += blen
        results.append((meta, blob))
    if pos != len(data):
        raise AssertionError(f"batch output has {len(data) - pos} trailing bytes")
    return results


def assert_malformed_rejected(binary: str) -> None:
    cases = {
        "huge-count-before-allocation": b"999999999999999999999\n",
        "count-exceeds-minimum-frame-size": b"3\n0\n0\n",
        "overrun-body": b"1\n10\nabc",
        "trailing-bytes": b"0\ntrailing",
        "non-digit-length": b"1\nx\n",
    }
    for name, payload in cases.items():
        proc = subprocess.run([binary, "redact-batch"], input=payload, capture_output=True)
        if proc.returncode == 0:
            raise AssertionError(f"{name}: malformed frame unexpectedly succeeded")
        if proc.stdout:
            raise AssertionError(f"{name}: malformed frame wrote stdout")


def assert_policy_args_rejected(binary: str) -> None:
    cases = {
        "negative-max-input": ("-1", "0"),
        "negative-budget": ("1", "-1"),
        "budget-without-cap": ("0", "1"),
        "non-numeric-policy": ("abc", "0"),
        "too-many-policy-args": ("1", "1", "extra"),
    }
    for name, args in cases.items():
        proc = subprocess.run(
            [binary, "redact-batch", *args],
            input=b"0\n",
            capture_output=True,
        )
        if proc.returncode == 0:
            raise AssertionError(f"{name}: malformed policy args unexpectedly succeeded")
        if proc.stdout:
            raise AssertionError(f"{name}: malformed policy args wrote stdout")


def main() -> None:
    binary = _binary()
    assert_malformed_rejected(binary)
    assert_policy_args_rejected(binary)
    files = sorted(p for p in INPUTS.iterdir() if p.is_file())
    if not files:
        print("SKIP: no fixtures under fixtures/inputs/; run tools/gen_fixtures.py first.")
        sys.exit(0)
    docs = [f.read_bytes() for f in files]

    expected = [run_redact_single(binary, d) for d in docs]

    proc = subprocess.run([binary, "redact-batch"], input=frame_batch(docs),
                          capture_output=True, check=True)
    results = parse_batch(proc.stdout)

    rows: list[str] = ["| fixture | findings | redacted-bytes |", "|---|---|---|"]
    fails = 0
    if len(results) != len(docs):
        print(f"FAIL: batch returned {len(results)} docs, expected {len(docs)}")
        sys.exit(1)

    for i, path in enumerate(files):
        exp_findings, exp_redacted = expected[i]
        meta, blob = results[i]
        if meta.get("i") != i:
            print(f"FAIL: {path.name}: batch index {meta.get('i')} != position {i} (order violated)")
            sys.exit(1)
        f_ok = meta.get("findings") == exp_findings and not meta.get("withheld", False)
        b_ok = blob == exp_redacted
        rows.append(f"| {path.name} | {'PASS' if f_ok else 'DIFF'} | {'PASS' if b_ok else 'DIFF'} |")
        if not (f_ok and b_ok):
            fails += 1

    print("\n".join(rows))
    print(f"\n{len(files)} fixture(s) — PASS={len(files) - fails}, DIFF={fails}")
    if fails:
        print("BATCH PARITY: FAIL")
        sys.exit(1)
    print("BATCH PARITY: PASS")


if __name__ == "__main__":
    main()
