#!/usr/bin/env python3
"""TIN-2708 C1 golden-file generator -- the PYTHON oracle.

Runs `prompt_toon.cli`'s own implementation (the reference oracle per
`docs/mythos-delivery-design.md` Sec7: "the Python implementation retires
into the golden-file parity oracle") over every fixture in
`fixtures/inputs/` and writes the results to `fixtures/golden/`.
`fixtures/` is gitignored -- golden files are regenerated by
`python3 tools/gen_golden.py`, never committed.

Two call paths per the C1 task brief:

1. **Direct function calls.** For every "text fixture" (plain text or
   markdown; everything except the two JSONL fixtures), `redact_text`,
   `normalize_text`, and `defang_text` are imported from
   `prompt_toon.cli` and called directly (no subprocess) -- this is the
   pure-Python semantics oracle these three functions define, and is
   also what `tools/parity_runner.py --functions` diffs the Chapel
   `ChapelEngine` methods against.
2. **Full CLI runs.** For every condense case (each text fixture run
   solo, plus one composite case that condenses the mixed-trust-tier
   pair together with a `--input-tier` override), this script shells
   out to `python3 -m prompt_toon condense --engine=python --id
   fixed-run-id ...` with `PROMPT_TOON_STATE_HOME` pointed at a fresh
   temporary directory per case, then copies `source-cards.jsonl`,
   `summary.md`, and `manifest.json` out of the run's output directory
   into `fixtures/golden/<case>/`. The two JSONL fixtures instead get a
   `python3 -m prompt_toon analyze --engine=python` run captured as
   `analyze.json` (condense's card/constraint extraction isn't a
   meaningful oracle for flat JSON row data).

`--engine=python` is passed explicitly everywhere it's accepted (matching
the parity runner's `--engine` sweep) even though it is also the CLI's
implicit default; if a future CLI revision ever *doesn't* accept
`--engine` this script still has to run in this repo, on this host, so
`run_condense`/`run_analyze` retry once without `--engine` on an
"unrecognized arguments" argparse failure and note the fallback on the
argv it printed.

## Masking rules (documented here per the C1 task brief)

Given a fixed `--id` and fixed input bytes, `condense`'s only
non-deterministic output is `now_utc()`, which is read once per run and
appears in `manifest.json`:

- `manifest.json`'s top-level `"generated_at"` key. This is masked
  *structurally*: the JSON is parsed, `generated_at` is overwritten with
  the literal string `"GENERATED_AT"`, and the object is re-serialized
  with `json.dumps(sort_keys=True, indent=2)` for byte-stable output --
  never a regex over the raw JSON text.
The summary no longer repeats the timestamp. `mask_summary_text` retains
the historical regex mask so this generator remains able to compare
legacy summary fixtures during format transitions.

`sha256` digests in `manifest.json`/`source-cards.jsonl` are a pure hash
of fixed input bytes, so they are already deterministic given a fixed
corpus and are left untouched -- no masking needed or applied. No other
artifact this script writes (`redact.out`/`normalize.out`/`defang.out`,
`analyze.json`) contains run-generated data of any kind.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
INPUTS = ROOT / "fixtures" / "inputs"
GOLDEN = ROOT / "fixtures" / "golden"

sys.path.insert(0, str(ROOT))
from prompt_toon.cli import defang_text, normalize_text, redact_text  # noqa: E402

FIXED_RUN_ID = "fixed-run-id"

# now_utc() in prompt_toon/cli.py emits exactly this shape (seconds
# precision, Z suffix, no microseconds).
TIMESTAMP_RE = re.compile(r"\b\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z\b")
TIMESTAMP_PLACEHOLDER = "GENERATED_AT"


@dataclass(frozen=True)
class TextFixture:
    name: str  # golden case dir, e.g. "01-homoglyph-secret"
    filename: str  # under fixtures/inputs/


@dataclass(frozen=True)
class CondenseCase:
    name: str
    inputs: tuple[str, ...]
    tier_overrides: dict[str, str] = field(default_factory=dict)
    trust_tier: str = "untrusted_tool_output"


@dataclass(frozen=True)
class JsonlFixture:
    name: str
    filename: str
    expect_toon: bool


# --------------------------------------------------------------------------
# fixture inventory (must match tools/gen_fixtures.py's CASES)
# --------------------------------------------------------------------------

TEXT_FIXTURES: list[TextFixture] = [
    TextFixture("01-homoglyph-secret", "01-homoglyph-secret.txt"),
    TextFixture("02-zw-split-secret", "02-zw-split-secret.txt"),
    TextFixture("03-bidi-tag-controls", "03-bidi-tag-controls.txt"),
    TextFixture("04-secret-classes", "04-secret-classes.txt"),
    TextFixture("05-homoglyph-imperatives", "05-homoglyph-imperatives.txt"),
    TextFixture("06-boundary-ascii", "06-boundary-ascii.txt"),
    TextFixture("07-boundary-unicode", "07-boundary-unicode.txt"),
    TextFixture("08-pem-split", "08-pem-split.txt"),
    TextFixture("09-mixed-doc", "09-mixed-doc.md"),
    TextFixture("10-clean-doc", "10-clean-doc.txt"),
    TextFixture("11-nul-and-crlf", "11-nul-and-crlf.txt"),
    TextFixture("12-confusable-full", "12-confusable-full.txt"),
    TextFixture("13-research-note", "13-research-note.md"),
    TextFixture("18-injected-literal-rescan", "18-injected-literal-rescan.txt"),
    TextFixture("16-trust-tier-pair-spec", "16-trust-tier-pair-spec.md"),
    TextFixture("17-trust-tier-pair-scrape", "17-trust-tier-pair-scrape.md"),
]

JSONL_FIXTURES: list[JsonlFixture] = [
    JsonlFixture("14-toon-uniform-rows", "14-toon-uniform-rows.jsonl", expect_toon=True),
    JsonlFixture("15-toon-ragged-rows", "15-toon-ragged-rows.jsonl", expect_toon=False),
]

# One condense case per text fixture (solo input) plus one composite case
# that condenses the mixed-trust-tier pair together with an --input-tier
# override on the spec file (the scrape file falls back to the case's
# default --trust-tier, untrusted_tool_output).
CONDENSE_CASES: list[CondenseCase] = [CondenseCase(f.name, (f.filename,)) for f in TEXT_FIXTURES] + [
    CondenseCase(
        "18-trust-tier-pair-combined",
        ("16-trust-tier-pair-spec.md", "17-trust-tier-pair-scrape.md"),
        tier_overrides={"fixtures/inputs/16-trust-tier-pair-spec.md": "repo_source"},
    )
]


# --------------------------------------------------------------------------
# masking
# --------------------------------------------------------------------------


def mask_manifest_bytes(raw: bytes) -> bytes:
    """Structural mask: parse, overwrite generated_at, re-serialize canonically."""
    obj = json.loads(raw.decode("utf-8"))
    if "generated_at" in obj:
        obj["generated_at"] = TIMESTAMP_PLACEHOLDER
    return (json.dumps(obj, indent=2, sort_keys=True) + "\n").encode("utf-8")


def mask_summary_text(text: str) -> str:
    """Prose mask: regex over the one line that embeds now_utc()'s output."""
    return TIMESTAMP_RE.sub(TIMESTAMP_PLACEHOLDER, text)


# --------------------------------------------------------------------------
# CLI plumbing
# --------------------------------------------------------------------------


def cli_env(extra: dict[str, str] | None = None) -> dict[str, str]:
    env = dict(os.environ)
    env["PYTHONPATH"] = str(ROOT)
    if extra:
        env.update(extra)
    return env


def run_cli(argv: list[str], *, extra_env: dict[str, str] | None = None) -> tuple[int, bytes, bytes]:
    proc = subprocess.run(
        [sys.executable, "-m", "prompt_toon", *argv],
        cwd=ROOT,
        capture_output=True,
        env=cli_env(extra_env),
    )
    return proc.returncode, proc.stdout, proc.stderr


def _is_unrecognized_engine_flag(rc: int, stderr: bytes) -> bool:
    text = stderr.decode("utf-8", errors="replace")
    return rc == 2 and "unrecognized arguments" in text and "--engine" in text


def run_condense(case: CondenseCase, engine: str = "python") -> tuple[int, dict[str, bytes], bytes]:
    """Run `condense --engine <engine> --id fixed-run-id` for `case` in a
    fresh temp state dir; return (rc, {artifact_name: masked_bytes}, stderr).
    `artifact_name` in {"source-cards.jsonl", "summary.md", "manifest.json"}.
    Missing artifacts (e.g. after a nonzero rc) are simply absent from the
    dict, never a KeyError.
    """
    with tempfile.TemporaryDirectory(prefix="ptoon-golden-") as tmp:
        state_home = Path(tmp) / "state"
        argv = [
            "condense",
            *(f"fixtures/inputs/{name}" for name in case.inputs),
            "--id",
            FIXED_RUN_ID,
            "--engine",
            engine,
        ]
        if case.trust_tier:
            argv += ["--trust-tier", case.trust_tier]
        for path, tier in case.tier_overrides.items():
            argv += ["--input-tier", f"{path}={tier}"]
        rc, _out, err = run_cli(argv, extra_env={"PROMPT_TOON_STATE_HOME": str(state_home)})
        if _is_unrecognized_engine_flag(rc, err) and engine == "python":
            # Forward-compat fallback: this CLI predates --engine. Python is
            # the implicit default, so re-run without the flag.
            argv = [a for a in argv if a not in ("--engine", engine)]
            rc, _out, err = run_cli(argv, extra_env={"PROMPT_TOON_STATE_HOME": str(state_home)})
        if rc != 0:
            return rc, {}, err
        out_dir = state_home / "runs" / FIXED_RUN_ID
        artifacts: dict[str, bytes] = {}
        summary_path = out_dir / "summary.md"
        if summary_path.exists():
            artifacts["summary.md"] = mask_summary_text(summary_path.read_text(encoding="utf-8")).encode("utf-8")
        cards_path = out_dir / "source-cards.jsonl"
        if cards_path.exists():
            artifacts["source-cards.jsonl"] = cards_path.read_bytes()
        manifest_path = out_dir / "manifest.json"
        if manifest_path.exists():
            artifacts["manifest.json"] = mask_manifest_bytes(manifest_path.read_bytes())
        return rc, artifacts, err


def run_analyze(fixture: JsonlFixture, engine: str = "python") -> tuple[int, bytes, bytes]:
    argv = ["analyze", f"fixtures/inputs/{fixture.filename}", "--engine", engine]
    rc, out, err = run_cli(argv)
    if _is_unrecognized_engine_flag(rc, err) and engine == "python":
        argv = [a for a in argv if a not in ("--engine", engine)]
        rc, out, err = run_cli(argv)
    if rc != 0:
        return rc, out, err
    obj = json.loads(out.decode("utf-8"))
    canonical = (json.dumps(obj, indent=2, sort_keys=True) + "\n").encode("utf-8")
    return rc, canonical, err


# --------------------------------------------------------------------------
# writers
# --------------------------------------------------------------------------


def write_case_file(case_name: str, artifact: str, data: bytes) -> Path:
    case_dir = GOLDEN / case_name
    case_dir.mkdir(parents=True, exist_ok=True)
    path = case_dir / artifact
    path.write_bytes(data)
    return path


def gen_text_fixture_oracle(fixture: TextFixture) -> list[Path]:
    text = (INPUTS / fixture.filename).read_bytes().decode("utf-8")
    redacted, findings = redact_text(text)
    redact_out = f"findings:{','.join(findings)}\n{redacted}".encode("utf-8")
    normalize_out = normalize_text(text).encode("utf-8")
    defang_out = defang_text(text).encode("utf-8")
    return [
        write_case_file(fixture.name, "redact.out", redact_out),
        write_case_file(fixture.name, "normalize.out", normalize_out),
        write_case_file(fixture.name, "defang.out", defang_out),
    ]


def gen_condense_case(case: CondenseCase) -> list[Path]:
    rc, artifacts, err = run_condense(case, engine="python")
    if rc != 0:
        raise RuntimeError(f"condense case {case.name!r} failed rc={rc}: {err.decode('utf-8', 'replace')[:500]}")
    return [write_case_file(case.name, name, data) for name, data in artifacts.items()]


def gen_jsonl_fixture(fixture: JsonlFixture) -> Path:
    rc, canonical, err = run_analyze(fixture, engine="python")
    if rc != 0:
        raise RuntimeError(f"analyze fixture {fixture.name!r} failed rc={rc}: {err.decode('utf-8', 'replace')[:500]}")
    report: dict[str, Any] = json.loads(canonical.decode("utf-8"))
    got_toon = report["recommendation"] == "toon"
    if got_toon != fixture.expect_toon:
        raise AssertionError(
            f"fixture {fixture.name!r}: expected recommendation=="
            f"{'toon' if fixture.expect_toon else 'compact-json'!r}, got {report['recommendation']!r}"
        )
    return write_case_file(fixture.name, "analyze.json", canonical)


def main() -> int:
    if not INPUTS.exists():
        print(f"error: {INPUTS} does not exist -- run tools/gen_fixtures.py first", file=sys.stderr)
        return 1

    written: list[Path] = []
    for fixture in TEXT_FIXTURES:
        written.extend(gen_text_fixture_oracle(fixture))
    for case in CONDENSE_CASES:
        written.extend(gen_condense_case(case))
    for jsonl_fixture in JSONL_FIXTURES:
        written.append(gen_jsonl_fixture(jsonl_fixture))

    for path in written:
        print(f"wrote {path.relative_to(ROOT)}")
    print(f"\n{len(written)} golden artifact(s) written across "
          f"{len(TEXT_FIXTURES)} text-fixture oracle case(s), "
          f"{len(CONDENSE_CASES)} condense case(s), "
          f"{len(JSONL_FIXTURES)} JSONL/analyze case(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
